baseURL = 'localhost'
title = 'Harley Eades'
theme = 'nab-dark'

[params]
subtitle = 'USAW Olympic Weightlifting Coach'
email = 'harley.eades@gmail.com'
copyright = '2026-2027 Harley Eades III'
instagram = 'harleyeadeslifts'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 2
  
  [[menus.main]]
    name = 'Academic Site'
    url = "https://hde.design"
    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[security.exec]
  allow = ["^(dart-)?sass$", "^go$", "^git$", "^node$", "^postcss$", "^tailwindcss$"]

[build]
  [buildStats]
    enable = true