baseURL = 'https://northaugustabarbell.github.io/'
languageCode = 'en-us'
title = 'W⋊B'
theme = 'nab-dark'

[params]
subtitle = 'TODO'
email = 'NorthAugustaBarbell@gmail.com'
copyright = '2026-2027 WKB'
instagram = 'todo'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 3
  
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 2

# [[menus.main]]
#     name = 'Services'
#     pageRef = '/services'
#     weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'
